# GitHub Pages Configuration
title: My Store
description: Fast, clean catalog for the latest patched (ReVanced, Revanced Extended, MorpheApp, RVX Morphed, and Revanced Advanced) Android apps and Magisk/KSU modules
url: https://hisok9.github.io/
repository: hisok9/hisok9.github.io

# Theme (optional)
theme: null

# Build settings
markdown: kramdown
exclude:
  - README.md
  - .gitignore
  - .nojekyll
